AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

inherit_from: .rubocop_todo.yml


# - Metrics Cops --------------------------------------------------------------

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'
